/*
 * Spartans_Horizon — all migrations, in order, as one script.
 * GENERATED by supabase/build_apply_all.sh. Do not edit by hand;
 * edit the individual migrations and regenerate.
 *
 * Safe to re-run: every statement is guarded (CREATE TABLE IF NOT EXISTS,
 * DROP POLICY IF EXISTS before CREATE POLICY, CREATE OR REPLACE FUNCTION,
 * DROP CONSTRAINT IF EXISTS before ADD CONSTRAINT).
 *
 * The SQL Editor runs a multi-statement script in one implicit transaction, so
 * if any statement fails the whole script rolls back — never a partial apply.
 */


-- ============================================================================
-- 20260719114729_create_spartan_core_tables.sql
-- ============================================================================

/*
# Create Spartan Core Tables

This migration creates four tables to power the Journal, Power Up, Goals,
and Streaks features of the Event Horizon / Spartan dashboard.

## Tables

### 1. journal_entries
Stores user journal entries for the Journal tab.
- id: UUID primary key
- title: Entry title (e.g. "Hackathon day 1")
- content: Full text body of the journal entry
- category: Free-form tag (e.g. "Tech", "Hackathon", "Learning")
- created_at / updated_at: Timestamps

### 2. skills
Stores skill panels for the Power Up tab.
- id: UUID primary key
- name: Skill / track name (e.g. "Reverse Engineering")
- category: Category label (e.g. "Security", "AI", "Web3")
- deadline: Optional target date for completing the skill
- completed_topics: Array of completed topic strings
- total_topics: How many topics the track contains
- progress: Integer percentage 0-100
- ai_feedback: Last AI-generated feedback text
- created_at

### 3. goals
Stores long-term and short-term goals for the Goals tab.
- id: UUID primary key
- title: Goal description
- goal_type: "long_term" or "short_term"
- deadline: Target completion date (ISO date)
- status: "active" | "completed" | "paused"
- description: Optional expanded note
- created_at

### 4. streak_logs
Stores daily streak proof submissions for the Streaks tab.
- id: UUID primary key
- log_date: The calendar date of the entry (unique per day)
- photo_url: URL of the uploaded proof photo (from Supabase Storage)
- verified: Whether the AI/system accepted it as valid
- note: Optional text note alongside the photo
- created_at

## Security
All tables use RLS with open anon + authenticated policies because this
is a single-user personal dashboard (no sign-in required).
*/

-- ── journal_entries ──────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS journal_entries (
  id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  title       text NOT NULL DEFAULT 'Untitled',
  content     text NOT NULL DEFAULT '',
  category    text NOT NULL DEFAULT 'General',
  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE journal_entries ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "je_select" ON journal_entries;
CREATE POLICY "je_select" ON journal_entries FOR SELECT TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "je_insert" ON journal_entries;
CREATE POLICY "je_insert" ON journal_entries FOR INSERT TO anon, authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "je_update" ON journal_entries;
CREATE POLICY "je_update" ON journal_entries FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "je_delete" ON journal_entries;
CREATE POLICY "je_delete" ON journal_entries FOR DELETE TO anon, authenticated USING (true);

-- Auto-update updated_at on edit
CREATE OR REPLACE FUNCTION update_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS je_updated_at ON journal_entries;
CREATE TRIGGER je_updated_at
  BEFORE UPDATE ON journal_entries
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();

-- ── skills ───────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS skills (
  id                uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name              text NOT NULL,
  category          text NOT NULL DEFAULT 'General',
  deadline          date,
  completed_topics  text[] NOT NULL DEFAULT '{}',
  total_topics      int NOT NULL DEFAULT 10,
  progress          int NOT NULL DEFAULT 0 CHECK (progress BETWEEN 0 AND 100),
  ai_feedback       text,
  created_at        timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE skills ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "skills_select" ON skills;
CREATE POLICY "skills_select" ON skills FOR SELECT TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "skills_insert" ON skills;
CREATE POLICY "skills_insert" ON skills FOR INSERT TO anon, authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "skills_update" ON skills;
CREATE POLICY "skills_update" ON skills FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "skills_delete" ON skills;
CREATE POLICY "skills_delete" ON skills FOR DELETE TO anon, authenticated USING (true);

-- ── goals ────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS goals (
  id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  title        text NOT NULL,
  goal_type    text NOT NULL CHECK (goal_type IN ('long_term', 'short_term')),
  deadline     date,
  status       text NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'completed', 'paused')),
  description  text,
  created_at   timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE goals ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "goals_select" ON goals;
CREATE POLICY "goals_select" ON goals FOR SELECT TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "goals_insert" ON goals;
CREATE POLICY "goals_insert" ON goals FOR INSERT TO anon, authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "goals_update" ON goals;
CREATE POLICY "goals_update" ON goals FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "goals_delete" ON goals;
CREATE POLICY "goals_delete" ON goals FOR DELETE TO anon, authenticated USING (true);

-- ── streak_logs ──────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS streak_logs (
  id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  log_date    date NOT NULL UNIQUE,
  photo_url   text,
  verified    boolean NOT NULL DEFAULT false,
  note        text,
  created_at  timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE streak_logs ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "streaks_select" ON streak_logs;
CREATE POLICY "streaks_select" ON streak_logs FOR SELECT TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "streaks_insert" ON streak_logs;
CREATE POLICY "streaks_insert" ON streak_logs FOR INSERT TO anon, authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "streaks_update" ON streak_logs;
CREATE POLICY "streaks_update" ON streak_logs FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "streaks_delete" ON streak_logs;
CREATE POLICY "streaks_delete" ON streak_logs FOR DELETE TO anon, authenticated USING (true);

-- Index on date for fast today-lookup
CREATE INDEX IF NOT EXISTS streak_logs_date_idx ON streak_logs(log_date);
CREATE INDEX IF NOT EXISTS goals_type_idx ON goals(goal_type, status);
CREATE INDEX IF NOT EXISTS je_created_idx ON journal_entries(created_at DESC);


-- ============================================================================
-- 20260720000000_create_profile_settings.sql
-- ============================================================================

/*
# Create profile_settings (repair migration)

`20260720170623_..._fix_rls_security_issues.sql` runs `ALTER TABLE profile_settings`,
but no migration in this repo ever created that table — it exists only in the original
hosted project, so replaying the migrations into a fresh Supabase project fails.

This migration recreates the table in its pre-fix shape (singleton row, id = 1) so the
later ALTERs apply cleanly. It is dated before the fix migration deliberately.

The table is not referenced anywhere in the frontend. It is recreated only to keep the
migration chain replayable; drop both it and its ALTERs if it is confirmed dead.
*/

CREATE TABLE IF NOT EXISTS profile_settings (
  id          int PRIMARY KEY DEFAULT 1,
  display_name text,
  accent      text NOT NULL DEFAULT 'ember',
  created_at  timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT profile_settings_id_check CHECK (id = 1)
);

ALTER TABLE profile_settings ENABLE ROW LEVEL SECURITY;


-- ============================================================================
-- 20260720170623_20260720_fix_rls_security_issues.sql.sql
-- ============================================================================

/*
# Fix RLS security issues and function search_path

## Summary
This migration closes two classes of security findings reported against the
Spartan / Event Horizon dashboard:

1. `public.update_updated_at` had a role-mutable `search_path` (Supabase's
   "Function Search Path Mutable" warning). We pin its `search_path` to `public`
   so a hostile role cannot shadow `now()` or other built-ins.
2. The RLS policies on `journal_entries`, `skills`, `goals`, `streak_logs`, and
   `profile_settings` used `USING (true)` / `WITH CHECK (true)` for INSERT,
   UPDATE, and DELETE. With `TO anon, authenticated` this effectively disabled
   RLS — any anon-key client could insert, edit, or delete any row. To fix this
   properly we convert the app to a signed-in, owner-scoped model: every row
   now carries a `user_id` (defaulted to `auth.uid()`), and each policy checks
   `auth.uid() = user_id`. SELECT stays open to `anon, authenticated` only on
   the shared `profile_settings` singleton; all per-user tables are
   `authenticated`-only.

## Tables modified
- `journal_entries` — add `user_id uuid NOT NULL DEFAULT auth.uid()` FK to
  `auth.users`, ON DELETE CASCADE. Index on `user_id`.
- `skills` — same `user_id` column + index.
- `goals` — same `user_id` column + index.
- `streak_logs` — same `user_id` column + index. The existing unique constraint
  on `log_date` is replaced with a composite unique constraint on
  `(user_id, log_date)` so multiple users can each log the same day.
- `profile_settings` — add `user_id uuid NOT NULL DEFAULT auth.uid()` FK to
  `auth.users`, ON DELETE CASCADE. Drop the `id = 1` check and the integer PK
  in favor of a per-user row keyed by `user_id` (unique). Existing rows are
  backfilled to a placeholder user id is NOT done — instead we keep the table
  empty (it has 0 rows) and let new users create their own row on first load.

## Security changes
- `ALTER FUNCTION public.update_updated_at(...) SET search_path = public`.
- Drop and recreate all INSERT/UPDATE/DELETE policies on the five tables so
  they enforce `auth.uid() = user_id`. SELECT policies on per-user tables are
  also scoped to the owner. `profile_settings` SELECT is `authenticated`-only
  and scoped to the owner.
- All policies use `TO authenticated` because the app now has a sign-in
  screen. The anon role receives no direct grants on these tables.

## Important notes
1. The frontend is being updated in the same task to add a sign-in / sign-up
   screen. Without an authenticated session, `auth.uid()` is null and every
   write fails the new RLS checks — the app would silently appear broken.
   Both halves ship together.
2. `user_id` columns are `NOT NULL DEFAULT auth.uid()` so client inserts that
   omit `user_id` (which is all of them in this codebase) still satisfy the
   INSERT policy's `WITH CHECK (auth.uid() = user_id)`.
3. Existing rows (the tables currently have 0 rows) would be orphaned by the
   new NOT NULL `user_id` constraint if any existed. With 0 rows there is no
   data loss. We never DROP tables or columns — only ADD columns and
   constraints.
4. The unique constraint on `streak_logs.log_date` is dropped and replaced
   with `UNIQUE (user_id, log_date)`. Dropping a constraint is safe and does
   not lose data.
*/

-- ── 1. Pin search_path on update_updated_at ──────────────────────────────
ALTER FUNCTION public.update_updated_at() SET search_path = public;

-- ── 2. journal_entries: add user_id + owner-scoped policies ──────────────
ALTER TABLE journal_entries
  ADD COLUMN IF NOT EXISTS user_id uuid
    NOT NULL DEFAULT auth.uid()
    REFERENCES auth.users(id) ON DELETE CASCADE;

CREATE INDEX IF NOT EXISTS journal_entries_user_id_idx ON journal_entries(user_id);

DROP POLICY IF EXISTS "je_select" ON journal_entries;
DROP POLICY IF EXISTS "je_insert" ON journal_entries;
DROP POLICY IF EXISTS "je_update" ON journal_entries;
DROP POLICY IF EXISTS "je_delete" ON journal_entries;

CREATE POLICY "je_select" ON journal_entries FOR SELECT
  TO authenticated USING (auth.uid() = user_id);
CREATE POLICY "je_insert" ON journal_entries FOR INSERT
  TO authenticated WITH CHECK (auth.uid() = user_id);
CREATE POLICY "je_update" ON journal_entries FOR UPDATE
  TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE POLICY "je_delete" ON journal_entries FOR DELETE
  TO authenticated USING (auth.uid() = user_id);

-- ── 3. skills: add user_id + owner-scoped policies ──────────────────────
ALTER TABLE skills
  ADD COLUMN IF NOT EXISTS user_id uuid
    NOT NULL DEFAULT auth.uid()
    REFERENCES auth.users(id) ON DELETE CASCADE;

CREATE INDEX IF NOT EXISTS skills_user_id_idx ON skills(user_id);

DROP POLICY IF EXISTS "skills_select" ON skills;
DROP POLICY IF EXISTS "skills_insert" ON skills;
DROP POLICY IF EXISTS "skills_update" ON skills;
DROP POLICY IF EXISTS "skills_delete" ON skills;

CREATE POLICY "skills_select" ON skills FOR SELECT
  TO authenticated USING (auth.uid() = user_id);
CREATE POLICY "skills_insert" ON skills FOR INSERT
  TO authenticated WITH CHECK (auth.uid() = user_id);
CREATE POLICY "skills_update" ON skills FOR UPDATE
  TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE POLICY "skills_delete" ON skills FOR DELETE
  TO authenticated USING (auth.uid() = user_id);

-- ── 4. goals: add user_id + owner-scoped policies ───────────────────────
ALTER TABLE goals
  ADD COLUMN IF NOT EXISTS user_id uuid
    NOT NULL DEFAULT auth.uid()
    REFERENCES auth.users(id) ON DELETE CASCADE;

CREATE INDEX IF NOT EXISTS goals_user_id_idx ON goals(user_id);

DROP POLICY IF EXISTS "goals_select" ON goals;
DROP POLICY IF EXISTS "goals_insert" ON goals;
DROP POLICY IF EXISTS "goals_update" ON goals;
DROP POLICY IF EXISTS "goals_delete" ON goals;

CREATE POLICY "goals_select" ON goals FOR SELECT
  TO authenticated USING (auth.uid() = user_id);
CREATE POLICY "goals_insert" ON goals FOR INSERT
  TO authenticated WITH CHECK (auth.uid() = user_id);
CREATE POLICY "goals_update" ON goals FOR UPDATE
  TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE POLICY "goals_delete" ON goals FOR DELETE
  TO authenticated USING (auth.uid() = user_id);

-- ── 5. streak_logs: add user_id, swap unique constraint, owner policies ──
ALTER TABLE streak_logs
  ADD COLUMN IF NOT EXISTS user_id uuid
    NOT NULL DEFAULT auth.uid()
    REFERENCES auth.users(id) ON DELETE CASCADE;

CREATE INDEX IF NOT EXISTS streak_logs_user_id_idx ON streak_logs(user_id);

-- Replace the global unique-on-log_date with a per-user unique constraint.
ALTER TABLE streak_logs DROP CONSTRAINT IF EXISTS streak_logs_log_date_key;
ALTER TABLE streak_logs DROP CONSTRAINT IF EXISTS streak_logs_user_log_date_key;
ALTER TABLE streak_logs ADD CONSTRAINT streak_logs_user_log_date_key
  UNIQUE (user_id, log_date);

DROP POLICY IF EXISTS "streaks_select" ON streak_logs;
DROP POLICY IF EXISTS "streaks_insert" ON streak_logs;
DROP POLICY IF EXISTS "streaks_update" ON streak_logs;
DROP POLICY IF EXISTS "streaks_delete" ON streak_logs;

CREATE POLICY "streaks_select" ON streak_logs FOR SELECT
  TO authenticated USING (auth.uid() = user_id);
CREATE POLICY "streaks_insert" ON streak_logs FOR INSERT
  TO authenticated WITH CHECK (auth.uid() = user_id);
CREATE POLICY "streaks_update" ON streak_logs FOR UPDATE
  TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE POLICY "streaks_delete" ON streak_logs FOR DELETE
  TO authenticated USING (auth.uid() = user_id);

-- ── 6. profile_settings: convert to per-user, owner-scoped policies ─────
-- The existing table is a singleton (id = 1, CHECK (id = 1)). We add a
-- user_id column and a per-user unique constraint, and drop the singleton
-- check so each user can own their own row. The integer PK stays as a
-- surrogate; the unique constraint on user_id enforces one-row-per-user.
ALTER TABLE profile_settings
  ADD COLUMN IF NOT EXISTS user_id uuid
    NOT NULL DEFAULT auth.uid()
    REFERENCES auth.users(id) ON DELETE CASCADE;

ALTER TABLE profile_settings DROP CONSTRAINT IF EXISTS profile_settings_user_id_key;
ALTER TABLE profile_settings ADD CONSTRAINT profile_settings_user_id_key
  UNIQUE (user_id);

-- Drop the singleton check so multiple users can each have a row.
ALTER TABLE profile_settings DROP CONSTRAINT IF EXISTS profile_settings_id_check;

CREATE INDEX IF NOT EXISTS profile_settings_user_id_idx ON profile_settings(user_id);

DROP POLICY IF EXISTS "profile_select" ON profile_settings;
DROP POLICY IF EXISTS "profile_insert" ON profile_settings;
DROP POLICY IF EXISTS "profile_update" ON profile_settings;
DROP POLICY IF EXISTS "profile_delete" ON profile_settings;

CREATE POLICY "profile_select" ON profile_settings FOR SELECT
  TO authenticated USING (auth.uid() = user_id);
CREATE POLICY "profile_insert" ON profile_settings FOR INSERT
  TO authenticated WITH CHECK (auth.uid() = user_id);
CREATE POLICY "profile_update" ON profile_settings FOR UPDATE
  TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE POLICY "profile_delete" ON profile_settings FOR DELETE
  TO authenticated USING (auth.uid() = user_id);


-- ============================================================================
-- 20260727120000_create_squads_and_users.sql
-- ============================================================================

/*
# Phase 1 — squads + users (username auth)

Creates the two tables everything else in Spartans_Horizon hangs off, and the
server-side entry points for squad membership.

## Auth model
Passwords are owned by Supabase Auth, not by us. The frontend turns a username into a
synthetic email (`<username>@spartans.local`) and calls the normal Supabase password
flow, so we inherit session handling, refresh tokens, and bcrypt hashing for free.

This is why `public.users` has NO `password_hash` column even though the build brief
lists one: storing a second copy of the password next to `auth.users.encrypted_password`
would be a duplicate secret with no reader. `public.users` is the *profile* half of the
identity — `auth.users` is the credential half, joined on id.

## Tables
- `squads` — id, name, join_code (the 6-char code members enter), created_by.
- `users`  — id (= auth.users.id), username, squad_id, current_streak,
             last_checkin_date. One row per account, created by trigger on signup.

## Privilege model
Clients may only change their own `username`. `squad_id`, `current_streak`, and
`last_checkin_date` are stripped from the `authenticated` role's UPDATE grant, and all
writes to `squads` are revoked outright. Membership and (later) streak math therefore
have to go through the SECURITY DEFINER functions below, which can enforce rules the
browser can't forge — this is the "do the streak math server-side" requirement from the
brief, enforced at the privilege layer rather than by convention.

## Functions
- `username_available(text)` — anon-callable pre-check for a friendly signup error.
- `create_squad(text)`       — creates a squad, joins the caller, returns the row.
- `join_squad(text)`         — joins the caller to a squad by join code.
- `handle_new_user()`        — trigger; materializes the profile row on signup.
- `current_squad_id()`       — RLS helper; avoids infinite recursion in the policy that
                               lets squadmates see each other.

## No extension dependency
Join codes are built with core `random()` over a fixed alphabet. This is deliberately
not cryptographic: a join code is a convenience lookup, not a secret. Security lives in
RLS and the SECURITY DEFINER RPCs — knowing a code lets you join a squad, which is the
entire point of having one. Uniqueness, not unguessability, is the requirement, and
that is enforced by the UNIQUE constraint plus the bounded retry loop below.

Everything else here uses `gen_random_uuid()`, core Postgres since 13, so this
migration needs no extensions at all.
*/

-- ── squads ───────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS squads (
  id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name        text NOT NULL CHECK (char_length(trim(name)) BETWEEN 2 AND 40),
  join_code   text NOT NULL UNIQUE CHECK (join_code ~ '^[A-Z0-9]{6}$'),
  created_by  uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at  timestamptz NOT NULL DEFAULT now()
);

-- ── users (profile half of the identity) ─────────────────────────────────
CREATE TABLE IF NOT EXISTS users (
  id                uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  username          text NOT NULL CHECK (username ~ '^[a-z0-9_]{3,20}$'),
  squad_id          uuid REFERENCES squads(id) ON DELETE SET NULL,
  current_streak    int NOT NULL DEFAULT 0 CHECK (current_streak >= 0),
  last_checkin_date date,
  created_at        timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS users_username_key ON users(username);
CREATE INDEX IF NOT EXISTS users_squad_id_idx ON users(squad_id);

-- ── Profile row is created by trigger, not by the client ─────────────────
-- If the client created it, a crash between signUp() and insert() would leave an
-- account that can authenticate but has no profile and no username.
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  INSERT INTO public.users (id, username)
  VALUES (
    NEW.id,
    lower(coalesce(NEW.raw_user_meta_data->>'username', split_part(NEW.email, '@', 1)))
  );
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- ── RLS helper ───────────────────────────────────────────────────────────
-- A policy on `users` that reads `users` would recurse. This function is owned by the
-- table owner, so its lookup is not itself subject to RLS.
CREATE OR REPLACE FUNCTION public.current_squad_id()
RETURNS uuid
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT squad_id FROM public.users WHERE id = auth.uid();
$$;

-- ── RLS: users ───────────────────────────────────────────────────────────
ALTER TABLE users ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "users_select" ON users;
DROP POLICY IF EXISTS "users_insert" ON users;
DROP POLICY IF EXISTS "users_update" ON users;

-- You can see yourself, and anyone in your squad (the squad roster).
CREATE POLICY "users_select" ON users FOR SELECT
  TO authenticated
  USING (
    id = auth.uid()
    OR (squad_id IS NOT NULL AND squad_id = public.current_squad_id())
  );

CREATE POLICY "users_insert" ON users FOR INSERT
  TO authenticated WITH CHECK (id = auth.uid());

-- Own row only, and squad_id must come out unchanged — joining a squad is
-- join_squad()'s job, not a client UPDATE with a guessed squad id.
CREATE POLICY "users_update" ON users FOR UPDATE
  TO authenticated
  USING (id = auth.uid())
  WITH CHECK (
    id = auth.uid()
    AND squad_id IS NOT DISTINCT FROM public.current_squad_id()
  );

-- No DELETE policy: accounts are removed via auth.users (cascades).

-- Column-level lockdown. RLS decides which rows; this decides which columns.
REVOKE ALL ON users FROM anon, authenticated;
GRANT SELECT ON users TO authenticated;
GRANT INSERT ON users TO authenticated;
GRANT UPDATE (username) ON users TO authenticated;

-- ── RLS: squads ──────────────────────────────────────────────────────────
ALTER TABLE squads ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "squads_select" ON squads;

-- Members can read their own squad (including its join code, to invite others).
CREATE POLICY "squads_select" ON squads FOR SELECT
  TO authenticated USING (id = public.current_squad_id());

-- Read-only to clients; creation and joining go through the RPCs below.
REVOKE ALL ON squads FROM anon, authenticated;
GRANT SELECT ON squads TO authenticated;

-- ── username_available ───────────────────────────────────────────────────
-- Callable by anon so the signup form can fail fast with a clear message. The unique
-- index remains the real guard against the check/insert race.
CREATE OR REPLACE FUNCTION public.username_available(p_username text)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT NOT EXISTS (SELECT 1 FROM public.users WHERE username = lower(trim(p_username)));
$$;

GRANT EXECUTE ON FUNCTION public.username_available(text) TO anon, authenticated;

-- ── create_squad ─────────────────────────────────────────────────────────
CREATE OR REPLACE FUNCTION public.create_squad(p_name text)
RETURNS squads
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  -- No 0/O, 1/I/L — join codes get read aloud and typed by hand.
  v_alphabet CONSTANT text := 'ABCDEFGHJKMNPQRSTUVWXYZ23456789';  -- 31 chars
  v_max_tries CONSTANT int := 10;
  v_uid   uuid := auth.uid();
  v_code  text;
  v_squad squads;
  v_tries int := 0;
BEGIN
  IF v_uid IS NULL THEN
    RAISE EXCEPTION 'Not authenticated';
  END IF;

  IF public.current_squad_id() IS NOT NULL THEN
    RAISE EXCEPTION 'You are already in a squad';
  END IF;

  -- 31^6 ≈ 887M codes, so a collision is remote; when one happens the UNIQUE
  -- constraint raises and we simply draw again. Bounded at v_max_tries so a
  -- pathological case fails loudly instead of spinning forever.
  LOOP
    v_tries := v_tries + 1;

    SELECT string_agg(substr(v_alphabet, floor(random() * length(v_alphabet))::int + 1, 1), '')
      INTO v_code
      FROM generate_series(1, 6);

    BEGIN
      INSERT INTO squads (name, join_code, created_by)
      VALUES (trim(p_name), v_code, v_uid)
      RETURNING * INTO v_squad;
      EXIT;
    EXCEPTION WHEN unique_violation THEN
      IF v_tries >= v_max_tries THEN
        RAISE EXCEPTION 'Could not allocate a join code, try again';
      END IF;
    END;
  END LOOP;

  UPDATE users SET squad_id = v_squad.id WHERE id = v_uid;
  RETURN v_squad;
END;
$$;

GRANT EXECUTE ON FUNCTION public.create_squad(text) TO authenticated;

-- ── join_squad ───────────────────────────────────────────────────────────
CREATE OR REPLACE FUNCTION public.join_squad(p_join_code text)
RETURNS squads
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_uid   uuid := auth.uid();
  v_squad squads;
BEGIN
  IF v_uid IS NULL THEN
    RAISE EXCEPTION 'Not authenticated';
  END IF;

  IF public.current_squad_id() IS NOT NULL THEN
    RAISE EXCEPTION 'You are already in a squad';
  END IF;

  SELECT * INTO v_squad FROM squads WHERE join_code = upper(trim(p_join_code));

  IF v_squad.id IS NULL THEN
    RAISE EXCEPTION 'No squad found with that code';
  END IF;

  UPDATE users SET squad_id = v_squad.id WHERE id = v_uid;
  RETURN v_squad;
END;
$$;

GRANT EXECUTE ON FUNCTION public.join_squad(text) TO authenticated;


-- ============================================================================
-- 20260728100000_create_learning_paths.sql
-- ============================================================================

/*
# Phase 2 — learning paths, modules, tasks

Three tables in a paths -> modules -> tasks hierarchy, matching the Phase 4 generator
output one-for-one so the AI layer can write straight into them without reshaping.

## Deviation from the build brief (agreed)
The brief listed a flat `learning_tasks` carrying `module_title`, `ai_leverage`, and
`estimated_days` per task, with no home for the required per-module `why_it_matters`.
Those four fields are module-level in the AI schema, so repeating them on every task
would duplicate data and lose `why_it_matters` entirely. `learning_modules` is inserted
between paths and tasks instead, and `learning_tasks.path_id` becomes `module_id`.

## user_id is denormalized onto all three tables
RLS on a task would otherwise need two joins to reach the owner. Every table carries
`user_id uuid NOT NULL DEFAULT auth.uid()` so policies stay single-predicate. The risk
of denormalization — a module whose owner drifts from its path's owner — is closed by
composite foreign keys: children reference `(id, user_id)` of their parent, so Postgres
makes divergence unrepresentable rather than merely discouraged.

## Sharing
Squadmates can READ each other's paths (progress visibility is the point of a squad);
only the owner can write. Journals stay private and are untouched by this migration.

## is_done is not client-writable
Tasks are ticked through `set_task_done()`, not a direct UPDATE. Phase 2 passes the
value straight through; Phase 4 adds proof verification inside that one function, so no
grants change and no client code moves when the AI lands.
*/

-- ── Helper: does the caller share a squad with this user? ────────────────
-- SECURITY DEFINER so the lookup is not itself filtered by users' own RLS.
CREATE OR REPLACE FUNCTION public.shares_squad_with(p_user_id uuid)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT p_user_id = auth.uid()
      OR EXISTS (
        SELECT 1
        FROM public.users me
        JOIN public.users them ON them.squad_id = me.squad_id
        WHERE me.id = auth.uid()
          AND them.id = p_user_id
          AND me.squad_id IS NOT NULL
      );
$$;

GRANT EXECUTE ON FUNCTION public.shares_squad_with(uuid) TO authenticated;

-- ── learning_paths ───────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS learning_paths (
  id                   uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id              uuid NOT NULL DEFAULT auth.uid()
                         REFERENCES auth.users(id) ON DELETE CASCADE,
  title                text NOT NULL CHECK (char_length(trim(title)) BETWEEN 1 AND 120),
  overview             text NOT NULL DEFAULT '',
  -- [{ "term": "...", "definition": "..." }] — the glossary defined before any
  -- module assumes knowledge.
  foundational_terms   jsonb NOT NULL DEFAULT '[]'::jsonb
                         CHECK (jsonb_typeof(foundational_terms) = 'array'),
  total_timeline_weeks int CHECK (total_timeline_weeks IS NULL OR total_timeline_weeks BETWEEN 1 AND 104),
  created_at           timestamptz NOT NULL DEFAULT now(),
  -- Target for the composite FK from learning_modules.
  UNIQUE (id, user_id)
);

CREATE INDEX IF NOT EXISTS learning_paths_user_id_idx ON learning_paths(user_id);

-- ── learning_modules ─────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS learning_modules (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  path_id         uuid NOT NULL,
  user_id         uuid NOT NULL DEFAULT auth.uid(),
  title           text NOT NULL CHECK (char_length(trim(title)) BETWEEN 1 AND 120),
  why_it_matters  text NOT NULL DEFAULT '',
  -- How to use AI tools to learn/apply THIS topic faster. Required by the brief on
  -- every module, so it is a column rather than a nullable afterthought.
  ai_leverage     text NOT NULL DEFAULT '',
  estimated_days  int CHECK (estimated_days IS NULL OR estimated_days BETWEEN 1 AND 365),
  sort_order      int NOT NULL DEFAULT 0,
  created_at      timestamptz NOT NULL DEFAULT now(),
  -- Owner cannot drift from the parent path's owner.
  FOREIGN KEY (path_id, user_id) REFERENCES learning_paths(id, user_id) ON DELETE CASCADE,
  UNIQUE (id, user_id)
);

CREATE INDEX IF NOT EXISTS learning_modules_path_idx ON learning_modules(path_id, sort_order);
CREATE INDEX IF NOT EXISTS learning_modules_user_id_idx ON learning_modules(user_id);

-- ── learning_tasks ───────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS learning_tasks (
  id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  module_id   uuid NOT NULL,
  user_id     uuid NOT NULL DEFAULT auth.uid(),
  label       text NOT NULL CHECK (char_length(trim(label)) BETWEEN 1 AND 200),
  proof_type  text NOT NULL DEFAULT 'text' CHECK (proof_type IN ('photo', 'link', 'text')),
  is_done     boolean NOT NULL DEFAULT false,
  -- Phase 4 fills these when a proof passes verification.
  done_at     timestamptz,
  sort_order  int NOT NULL DEFAULT 0,
  created_at  timestamptz NOT NULL DEFAULT now(),
  FOREIGN KEY (module_id, user_id) REFERENCES learning_modules(id, user_id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS learning_tasks_module_idx ON learning_tasks(module_id, sort_order);
CREATE INDEX IF NOT EXISTS learning_tasks_user_id_idx ON learning_tasks(user_id);

-- ── RLS ──────────────────────────────────────────────────────────────────
ALTER TABLE learning_paths   ENABLE ROW LEVEL SECURITY;
ALTER TABLE learning_modules ENABLE ROW LEVEL SECURITY;
ALTER TABLE learning_tasks   ENABLE ROW LEVEL SECURITY;

-- Read: you or your squad. Write: you only.
DROP POLICY IF EXISTS "lp_select" ON learning_paths;
DROP POLICY IF EXISTS "lp_insert" ON learning_paths;
DROP POLICY IF EXISTS "lp_update" ON learning_paths;
DROP POLICY IF EXISTS "lp_delete" ON learning_paths;

CREATE POLICY "lp_select" ON learning_paths FOR SELECT
  TO authenticated USING (public.shares_squad_with(user_id));
CREATE POLICY "lp_insert" ON learning_paths FOR INSERT
  TO authenticated WITH CHECK (user_id = auth.uid());
CREATE POLICY "lp_update" ON learning_paths FOR UPDATE
  TO authenticated USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());
CREATE POLICY "lp_delete" ON learning_paths FOR DELETE
  TO authenticated USING (user_id = auth.uid());

DROP POLICY IF EXISTS "lm_select" ON learning_modules;
DROP POLICY IF EXISTS "lm_insert" ON learning_modules;
DROP POLICY IF EXISTS "lm_update" ON learning_modules;
DROP POLICY IF EXISTS "lm_delete" ON learning_modules;

CREATE POLICY "lm_select" ON learning_modules FOR SELECT
  TO authenticated USING (public.shares_squad_with(user_id));
CREATE POLICY "lm_insert" ON learning_modules FOR INSERT
  TO authenticated WITH CHECK (user_id = auth.uid());
CREATE POLICY "lm_update" ON learning_modules FOR UPDATE
  TO authenticated USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());
CREATE POLICY "lm_delete" ON learning_modules FOR DELETE
  TO authenticated USING (user_id = auth.uid());

DROP POLICY IF EXISTS "lt_select" ON learning_tasks;
DROP POLICY IF EXISTS "lt_insert" ON learning_tasks;
DROP POLICY IF EXISTS "lt_update" ON learning_tasks;
DROP POLICY IF EXISTS "lt_delete" ON learning_tasks;

CREATE POLICY "lt_select" ON learning_tasks FOR SELECT
  TO authenticated USING (public.shares_squad_with(user_id));
CREATE POLICY "lt_insert" ON learning_tasks FOR INSERT
  TO authenticated WITH CHECK (user_id = auth.uid());
CREATE POLICY "lt_update" ON learning_tasks FOR UPDATE
  TO authenticated USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());
CREATE POLICY "lt_delete" ON learning_tasks FOR DELETE
  TO authenticated USING (user_id = auth.uid());

-- ── Column grants ────────────────────────────────────────────────────────
-- RLS picks the rows; these pick the columns. `user_id` is never client-writable —
-- the DEFAULT supplies it — and `is_done` / `done_at` belong to set_task_done().
REVOKE ALL ON learning_paths, learning_modules, learning_tasks FROM anon, authenticated;

GRANT SELECT, INSERT, DELETE ON learning_paths TO authenticated;
GRANT UPDATE (title, overview, foundational_terms, total_timeline_weeks)
  ON learning_paths TO authenticated;

GRANT SELECT, INSERT, DELETE ON learning_modules TO authenticated;
GRANT UPDATE (title, why_it_matters, ai_leverage, estimated_days, sort_order)
  ON learning_modules TO authenticated;

GRANT SELECT, INSERT, DELETE ON learning_tasks TO authenticated;
GRANT UPDATE (label, proof_type, sort_order) ON learning_tasks TO authenticated;

-- ── set_task_done ────────────────────────────────────────────────────────
-- The single seam where a checkbox changes state. Phase 4 adds proof verification
-- here; nothing else has to move.
CREATE OR REPLACE FUNCTION public.set_task_done(p_task_id uuid, p_done boolean)
RETURNS learning_tasks
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_uid  uuid := auth.uid();
  v_task learning_tasks;
BEGIN
  IF v_uid IS NULL THEN
    RAISE EXCEPTION 'Not authenticated';
  END IF;

  -- SECURITY DEFINER bypasses RLS, so ownership is checked explicitly here.
  SELECT * INTO v_task FROM learning_tasks WHERE id = p_task_id;

  IF v_task.id IS NULL THEN
    RAISE EXCEPTION 'Task not found';
  END IF;

  IF v_task.user_id <> v_uid THEN
    RAISE EXCEPTION 'That task belongs to someone else';
  END IF;

  UPDATE learning_tasks
     SET is_done = p_done,
         done_at = CASE WHEN p_done THEN now() ELSE NULL END
   WHERE id = p_task_id
  RETURNING * INTO v_task;

  RETURN v_task;
END;
$$;

GRANT EXECUTE ON FUNCTION public.set_task_done(uuid, boolean) TO authenticated;


-- ============================================================================
-- 20260730120000_record_checkin.sql
-- ============================================================================

/*
# record_checkin — server-side streak math

The streak counter had no server-side path. `StreaksPage` wrote `streak_logs.verified`
straight from the browser and nothing ever touched `users.current_streak`, so the
dashboard number stayed at 0 while the UI claimed "+1 streak day added". This closes
both halves: the increment now happens in the database, and the client can no longer
write the fields it depends on.

## Why the caller is identified by argument, not auth.uid()
`set_task_done()` runs on the caller's own JWT, which is right for a task the user is
allowed to tick manually. A streak is different — it may only advance on a Gemini
verdict, so the *user* must not be able to call this at all. EXECUTE is therefore
granted to `service_role` only, which means `auth.uid()` is NULL inside the function
and ownership has to arrive as `p_user_id`.

That argument is not client input. The `verify-proof` Edge Function resolves it from the
caller's JWT via `auth.getUser()` before invoking this, so a forged body cannot check in
as someone else.

## Streak rule
- last check-in was today      -> no-op, streak unchanged (idempotent re-submission)
- last check-in was yesterday  -> current_streak + 1
- anything else (null, gap)    -> reset to 1

`SELECT ... FOR UPDATE` serialises concurrent submissions so two requests can't both
read the same streak and each add one.
*/

CREATE OR REPLACE FUNCTION public.record_checkin(
  p_user_id  uuid,
  p_note     text DEFAULT NULL,
  p_log_date date DEFAULT NULL
)
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_today   date := coalesce(p_log_date, current_date);
  v_last    date;
  v_streak  int;
  v_already boolean := false;
BEGIN
  IF p_user_id IS NULL THEN
    RAISE EXCEPTION 'p_user_id is required';
  END IF;

  -- Row lock: without it two concurrent check-ins could both read streak = N.
  SELECT last_checkin_date, current_streak
    INTO v_last, v_streak
    FROM users
   WHERE id = p_user_id
     FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'No profile row for that user';
  END IF;

  IF v_last = v_today THEN
    v_already := true;                 -- already counted today
  ELSIF v_last = v_today - 1 THEN
    v_streak := v_streak + 1;          -- consecutive day
  ELSE
    v_streak := 1;                     -- first check-in, or the chain broke
  END IF;

  IF NOT v_already THEN
    UPDATE users
       SET current_streak    = v_streak,
           last_checkin_date = v_today
     WHERE id = p_user_id;
  END IF;

  -- One verified log per user per day; re-submission refreshes the note.
  INSERT INTO streak_logs (user_id, log_date, verified, note)
  VALUES (p_user_id, v_today, true, p_note)
  ON CONFLICT (user_id, log_date) DO UPDATE
     SET verified = true,
         note     = coalesce(excluded.note, streak_logs.note);

  RETURN json_build_object(
    'current_streak',     v_streak,
    'last_checkin_date',  v_today,
    'already_checked_in', v_already
  );
END;
$$;

-- EXECUTE defaults to PUBLIC on a new function, so the REVOKE is load-bearing:
-- without it any signed-in user could call this and hand themselves a streak.
REVOKE ALL ON FUNCTION public.record_checkin(uuid, text, date) FROM public;
REVOKE ALL ON FUNCTION public.record_checkin(uuid, text, date) FROM anon, authenticated;
GRANT EXECUTE ON FUNCTION public.record_checkin(uuid, text, date) TO service_role;

-- ── Lock down streak_logs ────────────────────────────────────────────────
-- The client reads its own history to draw the grid and nothing more. Every write
-- goes through record_checkin(), so `verified` is no longer client-settable.
REVOKE ALL ON streak_logs FROM anon, authenticated;
GRANT SELECT ON streak_logs TO authenticated;

-- Write policies would now be dead letters — no grant backs them. Drop them so the
-- policy list stops implying the client can write here.
DROP POLICY IF EXISTS "streaks_insert" ON streak_logs;
DROP POLICY IF EXISTS "streaks_update" ON streak_logs;
DROP POLICY IF EXISTS "streaks_delete" ON streak_logs;

-- Owner-scoped read stays.
DROP POLICY IF EXISTS "streaks_select" ON streak_logs;
CREATE POLICY "streaks_select" ON streak_logs FOR SELECT
  TO authenticated USING (auth.uid() = user_id);

/*
`users.current_streak` and `users.last_checkin_date` were already unreachable —
20260727120000 does `REVOKE ALL ON users` then grants only
`SELECT, INSERT, UPDATE (username)`. Re-asserted here so this migration is
self-contained and a fresh replay cannot leave them writable.
*/
REVOKE ALL ON users FROM anon, authenticated;
GRANT SELECT ON users TO authenticated;
GRANT INSERT ON users TO authenticated;
GRANT UPDATE (username) ON users TO authenticated;


-- ============================================================================
-- 20260731090000_create_missions.sql
-- ============================================================================

/*
# missions — private, per-user deadlines for the "Next Missions" home section

## Schema decision: a dedicated table, not a user_id path on `projects`
`projects` does not exist. It was specified in the build brief for Phase 3 but never
built, so there is nothing to add a user_id path to. The real choice was between a new
`missions` table and reusing `goals`, which is already owner-scoped and already carries
`title` + `deadline`.

Dedicated table, because reusing `goals` would mean either widening its
`goal_type IN ('long_term','short_term')` CHECK to include a third kind — mutating a
constraint GoalsPage depends on and entangling two features — or filing missions under a
goal type they are not. `goals` also carries `status` and `description` semantics that a
mission (title + deadline) does not need. A separate table keeps GoalsPage untouched and
lets priority/progress land here later without touching goals.

## Privacy
Owner-only, and unlike `learning_paths` there is NO squad read: these are private, so
the SELECT policy is `user_id = auth.uid()` rather than `shares_squad_with()`.

## Room for priority/progress
Both columns exist now, nullable, so adding them to the UI later needs no schema change.
They are deliberately left OUT of the UPDATE grant: with no UI behind them, nothing
should be able to set a priority or a progress percentage yet. Enabling them later is
one explicit GRANT — which is the point, since a fabricated "78% CRITICAL" is exactly
the kind of fake signal this app has been removing.
*/

CREATE TABLE IF NOT EXISTS missions (
  id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id     uuid NOT NULL DEFAULT auth.uid()
                REFERENCES auth.users(id) ON DELETE CASCADE,
  title       text NOT NULL CHECK (char_length(trim(title)) BETWEEN 1 AND 120),
  deadline    date,
  -- Reserved. Nullable + CHECK that tolerates NULL, so no backfill is ever needed.
  priority    text CHECK (priority IS NULL OR priority IN ('critical', 'high', 'medium', 'low')),
  progress    int  CHECK (progress IS NULL OR progress BETWEEN 0 AND 100),
  created_at  timestamptz NOT NULL DEFAULT now()
);

-- Home section sorts by nearest deadline for one user.
CREATE INDEX IF NOT EXISTS missions_user_deadline_idx ON missions(user_id, deadline);

ALTER TABLE missions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "missions_select" ON missions;
DROP POLICY IF EXISTS "missions_insert" ON missions;
DROP POLICY IF EXISTS "missions_update" ON missions;
DROP POLICY IF EXISTS "missions_delete" ON missions;

CREATE POLICY "missions_select" ON missions FOR SELECT
  TO authenticated USING (user_id = auth.uid());
CREATE POLICY "missions_insert" ON missions FOR INSERT
  TO authenticated WITH CHECK (user_id = auth.uid());
CREATE POLICY "missions_update" ON missions FOR UPDATE
  TO authenticated USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());
CREATE POLICY "missions_delete" ON missions FOR DELETE
  TO authenticated USING (user_id = auth.uid());

-- RLS picks the rows; grants pick the columns. `user_id` is never client-writable —
-- the DEFAULT supplies it — and priority/progress stay ungranted until they have UI.
REVOKE ALL ON missions FROM anon, authenticated;
GRANT SELECT, INSERT, DELETE ON missions TO authenticated;
GRANT UPDATE (title, deadline) ON missions TO authenticated;

-- PostgREST caches the schema; without this the table 404s until the cache refreshes.
NOTIFY pgrst, 'reload schema';


-- ============================================================================
-- 20260731160000_create_mission_phases.sql
-- ============================================================================

/*
# mission_phases — expandable phase timeline per mission

## Prerequisite: missions needs UNIQUE (id, user_id)
`missions` was created without it, so the composite-FK pattern used by
learning_modules/learning_tasks has nothing to point at. This migration adds that
constraint first. It is additive and cannot fail on existing data — `id` is already the
primary key, so (id, user_id) is unique by construction.

## Objects created
- CONSTRAINT missions_id_user_key  UNIQUE (id, user_id) ON missions   [prerequisite]
- TABLE      mission_phases
- INDEX      mission_phases_mission_order_idx, mission_phases_user_id_idx

## Ownership cannot drift
`FOREIGN KEY (mission_id, user_id) REFERENCES missions(id, user_id)` — a phase whose
owner differs from its mission's owner is unrepresentable, not merely discouraged. Same
pattern as learning_modules -> learning_paths.

## Privacy
Owner-only, `user_id = auth.uid()`, matching `missions`. No squad read: phases are as
private as the mission they belong to.

## Grants
UPDATE is limited to the user-editable columns. `user_id` and `mission_id` are excluded,
so a phase can never be reassigned to another user or moved to another mission from the
client — the DEFAULT and the insert supply them once.
*/

-- ── Prerequisite constraint on missions ─────────────────────────────────
ALTER TABLE missions DROP CONSTRAINT IF EXISTS missions_id_user_key;
ALTER TABLE missions ADD CONSTRAINT missions_id_user_key UNIQUE (id, user_id);

-- ── mission_phases ──────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS mission_phases (
  id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  mission_id   uuid NOT NULL,
  user_id      uuid NOT NULL DEFAULT auth.uid(),
  title        text NOT NULL CHECK (char_length(trim(title)) BETWEEN 1 AND 120),
  description  text,
  status       text NOT NULL DEFAULT 'pending'
                 CHECK (status IN ('pending', 'live', 'completed')),
  target_date  date,
  order_index  int NOT NULL DEFAULT 0,
  created_at   timestamptz NOT NULL DEFAULT now(),
  FOREIGN KEY (mission_id, user_id) REFERENCES missions(id, user_id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS mission_phases_mission_order_idx
  ON mission_phases(mission_id, order_index);
CREATE INDEX IF NOT EXISTS mission_phases_user_id_idx ON mission_phases(user_id);

-- ── RLS ─────────────────────────────────────────────────────────────────
ALTER TABLE mission_phases ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "mission_phases_select" ON mission_phases;
DROP POLICY IF EXISTS "mission_phases_insert" ON mission_phases;
DROP POLICY IF EXISTS "mission_phases_update" ON mission_phases;
DROP POLICY IF EXISTS "mission_phases_delete" ON mission_phases;

CREATE POLICY "mission_phases_select" ON mission_phases FOR SELECT
  TO authenticated USING (user_id = auth.uid());
CREATE POLICY "mission_phases_insert" ON mission_phases FOR INSERT
  TO authenticated WITH CHECK (user_id = auth.uid());
CREATE POLICY "mission_phases_update" ON mission_phases FOR UPDATE
  TO authenticated USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());
CREATE POLICY "mission_phases_delete" ON mission_phases FOR DELETE
  TO authenticated USING (user_id = auth.uid());

-- ── Grants: RLS picks rows, these pick columns ──────────────────────────
REVOKE ALL ON mission_phases FROM anon, authenticated;
GRANT SELECT, INSERT, DELETE ON mission_phases TO authenticated;
GRANT UPDATE (title, description, status, target_date, order_index)
  ON mission_phases TO authenticated;

NOTIFY pgrst, 'reload schema';


-- ============================================================================
-- 20260731170000_create_habits.sql
-- ============================================================================

/*
# habits — real, per-user daily habits with AI-verified completions

Replaces the hardcoded `HABITS` / `TODAY_ITEMS` fixtures in `src/data.ts`, whose ticks
were decoration — a literal `done: true/false` that never changed. This is the same
category of fake signal the app has been removing (the "78% CRITICAL" progress bars, the
canned AI verdicts). A habit is now ticked only by a passing Gemini verdict on a photo,
exactly like a streak check-in.

## Tables
- `habits`             — id, user_id, title, icon, active, sort_order, created_at.
                         Owner-only, mirrors `missions`.
- `habit_completions`  — one verified completion per habit per day
                         (UNIQUE (user_id, habit_id, log_date)). NOT client-writable:
                         SELECT is granted, every write goes through
                         record_habit_completion(), same shape as `streak_logs`.

## Ownership cannot drift
`habit_completions` carries a composite FK to `habits(id, user_id)`, so a completion
whose owner differs from its habit's owner is unrepresentable — the same structural
guarantee learning_tasks -> learning_modules uses. That needs UNIQUE (id, user_id) on
`habits`, added below (id is already the PK, so the pair is unique by construction).

## Streak coupling (product decision)
A verified habit also advances the daily streak: record_habit_completion() calls
record_checkin() after recording the completion. Ticking any habit *is* that day's
check-in. record_checkin() is idempotent per day, so ticking a second habit the same day
records the completion without double-counting the streak.

## Seeding
Every user starts with the four original demo habits (Workout / Deep work block /
Read 20 pages / Sleep by 11pm). New users are seeded by the signup trigger; existing
users are backfilled once at the bottom of this migration. seed_default_habits() is the
single source of truth for that default set and is a no-op if the user already has any.
*/

-- ── habits ────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS habits (
  id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id     uuid NOT NULL DEFAULT auth.uid()
                REFERENCES auth.users(id) ON DELETE CASCADE,
  title       text NOT NULL CHECK (char_length(trim(title)) BETWEEN 1 AND 80),
  -- lucide icon name; the client maps a known set to components with a fallback.
  icon        text NOT NULL DEFAULT 'Flame',
  active       boolean NOT NULL DEFAULT true,
  sort_order  int NOT NULL DEFAULT 0,
  created_at  timestamptz NOT NULL DEFAULT now(),
  -- Prerequisite for the composite FK from habit_completions.
  CONSTRAINT habits_id_user_key UNIQUE (id, user_id)
);

CREATE INDEX IF NOT EXISTS habits_user_sort_idx ON habits(user_id, sort_order);

ALTER TABLE habits ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "habits_select" ON habits;
DROP POLICY IF EXISTS "habits_insert" ON habits;
DROP POLICY IF EXISTS "habits_update" ON habits;
DROP POLICY IF EXISTS "habits_delete" ON habits;

CREATE POLICY "habits_select" ON habits FOR SELECT
  TO authenticated USING (user_id = auth.uid());
CREATE POLICY "habits_insert" ON habits FOR INSERT
  TO authenticated WITH CHECK (user_id = auth.uid());
CREATE POLICY "habits_update" ON habits FOR UPDATE
  TO authenticated USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());
CREATE POLICY "habits_delete" ON habits FOR DELETE
  TO authenticated USING (user_id = auth.uid());

-- RLS picks rows; grants pick columns. `user_id` is never client-writable (the DEFAULT
-- supplies it); a habit can be renamed, reordered, or archived, nothing else.
REVOKE ALL ON habits FROM anon, authenticated;
GRANT SELECT, INSERT, DELETE ON habits TO authenticated;
GRANT UPDATE (title, icon, active, sort_order) ON habits TO authenticated;

-- ── habit_completions ─────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS habit_completions (
  id               uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id          uuid NOT NULL DEFAULT auth.uid(),
  habit_id         uuid NOT NULL,
  log_date         date NOT NULL DEFAULT current_date,
  verified         boolean NOT NULL DEFAULT false,
  evaluation_text  text,
  created_at       timestamptz NOT NULL DEFAULT now(),
  FOREIGN KEY (habit_id, user_id) REFERENCES habits(id, user_id) ON DELETE CASCADE,
  -- One completion per habit per day; re-submission refreshes it, never duplicates.
  CONSTRAINT habit_completions_unique_day UNIQUE (user_id, habit_id, log_date)
);

CREATE INDEX IF NOT EXISTS habit_completions_user_date_idx
  ON habit_completions(user_id, log_date);

ALTER TABLE habit_completions ENABLE ROW LEVEL SECURITY;

-- Read-only to the client, exactly like streak_logs. Every write goes through
-- record_habit_completion(), so `verified` is not client-settable and no photo verdict
-- can be forged from the browser.
DROP POLICY IF EXISTS "habit_completions_select" ON habit_completions;
CREATE POLICY "habit_completions_select" ON habit_completions FOR SELECT
  TO authenticated USING (user_id = auth.uid());

REVOKE ALL ON habit_completions FROM anon, authenticated;
GRANT SELECT ON habit_completions TO authenticated;

-- ── record_habit_completion — the only write path ─────────────────────────
/*
Same shape and rationale as record_checkin(): EXECUTE is service_role-only, so a signed-in
user cannot call it and hand themselves a completion. `auth.uid()` is therefore NULL
inside it and ownership arrives as p_user_id — which the verify-proof Edge Function
resolves from the verified JWT, never from the request body.

The habit is validated to belong to the caller and to be active before anything is
recorded, so a stale or foreign habit_id fails loudly instead of writing an orphan.

On success it also advances the streak by calling record_checkin(). record_checkin() is
idempotent per day, so a second habit ticked the same day records its own completion
without moving the streak twice.
*/
CREATE OR REPLACE FUNCTION public.record_habit_completion(
  p_user_id   uuid,
  p_habit_id  uuid,
  p_note      text DEFAULT NULL
)
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_today   date := current_date;
  v_title   text;
  v_streak  json;
BEGIN
  IF p_user_id IS NULL OR p_habit_id IS NULL THEN
    RAISE EXCEPTION 'p_user_id and p_habit_id are required';
  END IF;

  SELECT title INTO v_title
    FROM habits
   WHERE id = p_habit_id AND user_id = p_user_id AND active;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'No active habit % for that user', p_habit_id;
  END IF;

  INSERT INTO habit_completions (user_id, habit_id, log_date, verified, evaluation_text)
  VALUES (p_user_id, p_habit_id, v_today, true, p_note)
  ON CONFLICT (user_id, habit_id, log_date) DO UPDATE
     SET verified        = true,
         evaluation_text = coalesce(excluded.evaluation_text, habit_completions.evaluation_text);

  -- A verified habit is the day's check-in. Idempotent, so ticking more habits today
  -- keeps the streak where it is rather than inflating it.
  v_streak := record_checkin(p_user_id, p_note);

  RETURN json_build_object(
    'habit_id',  p_habit_id,
    'title',     v_title,
    'log_date',  v_today,
    'streak',    v_streak
  );
END;
$$;

-- EXECUTE defaults to PUBLIC; the REVOKE is load-bearing, or any signed-in user could
-- tick a habit (and thus their streak) with no photo at all.
REVOKE ALL ON FUNCTION public.record_habit_completion(uuid, uuid, text) FROM public;
REVOKE ALL ON FUNCTION public.record_habit_completion(uuid, uuid, text) FROM anon, authenticated;
GRANT EXECUTE ON FUNCTION public.record_habit_completion(uuid, uuid, text) TO service_role;

-- ── Default habit set + seeding ───────────────────────────────────────────
-- Single source of truth for the starter habits. SECURITY DEFINER so it can write
-- regardless of the caller's grants; no-op if the user already has any habit, which
-- makes both the trigger and the backfill idempotent.
CREATE OR REPLACE FUNCTION public.seed_default_habits(p_user_id uuid)
RETURNS void
LANGUAGE sql
SECURITY DEFINER
SET search_path = public
AS $$
  INSERT INTO habits (user_id, title, icon, sort_order)
  SELECT p_user_id, d.title, d.icon, d.sort_order
  FROM (VALUES
    ('Workout',         'Dumbbell', 0),
    ('Deep work block', 'Code2',    1),
    ('Read 20 pages',   'BookOpen', 2),
    ('Sleep by 11pm',   'Moon',     3)
  ) AS d(title, icon, sort_order)
  WHERE NOT EXISTS (SELECT 1 FROM habits h WHERE h.user_id = p_user_id);
$$;

REVOKE ALL ON FUNCTION public.seed_default_habits(uuid) FROM public;
REVOKE ALL ON FUNCTION public.seed_default_habits(uuid) FROM anon, authenticated;

-- ── Extend the signup trigger to seed habits ──────────────────────────────
-- Re-declares handle_new_user() from 20260727120000 with one added call. Kept as a full
-- CREATE OR REPLACE (not an ALTER) so a fresh replay ends with this definition; the
-- profile-row insert is unchanged.
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  INSERT INTO public.users (id, username)
  VALUES (
    NEW.id,
    lower(coalesce(NEW.raw_user_meta_data->>'username', split_part(NEW.email, '@', 1)))
  );

  PERFORM public.seed_default_habits(NEW.id);

  RETURN NEW;
END;
$$;

-- ── Backfill existing users ───────────────────────────────────────────────
-- The trigger only fires on new signups; give everyone already here the same starter
-- set. seed_default_habits() skips anyone who already has a habit, so this is safe to
-- replay.
DO $$
DECLARE
  v_id uuid;
BEGIN
  FOR v_id IN SELECT id FROM public.users LOOP
    PERFORM public.seed_default_habits(v_id);
  END LOOP;
END $$;

NOTIFY pgrst, 'reload schema';


-- ============================================================================
-- 20260731180000_fix_goals_grants.sql
-- ============================================================================

/*
# goals — grant the privileges that were never issued

`goals` is the one live table that got RLS policies but no GRANTs. The 20260720170623
migration added owner-scoped policies for it, and every later migration granted its own
tables explicitly — `goals` was skipped. This project does not hand out blanket default
privileges (anon already gets 42501 on it), so `authenticated` ended up with nothing:

    has_table_privilege('authenticated','public.goals', ...)
      SELECT  false
      INSERT  false
      UPDATE  false
      DELETE  false

Policies alone are not access. RLS narrows what a role can reach; a GRANT is what gives
it any reach at all. With none, every GoalsPage query failed at the table-privilege
layer before RLS was ever consulted — and because the client discarded the error, it
looked like an empty table rather than a permission failure.

## Grants issued
- SELECT, INSERT, DELETE — same shape as missions/learning_paths.
- UPDATE limited to the user-editable columns. `user_id` stays ungranted so a goal can
  never be reassigned to another user; `id` and `created_at` stay ungranted as identity
  and provenance.

No policy changes: the owner-scoped policies from 20260720170623 are already correct and
now actually get exercised.
*/

REVOKE ALL ON goals FROM anon, authenticated;

GRANT SELECT, INSERT, DELETE ON goals TO authenticated;
GRANT UPDATE (title, goal_type, deadline, status, description) ON goals TO authenticated;

NOTIFY pgrst, 'reload schema';

