#!/usr/bin/env bash
# Regenerate supabase/apply_all.sql from supabase/migrations/.
#
# apply_all.sql is a build artifact: every migration concatenated in filename order for
# a single paste into the SQL Editor. The individual migrations remain the source of
# truth — edit those, then run this.
#
# Usage:  ./supabase/build_apply_all.sh [--copy]
#           --copy  also place the result on the clipboard (needs xclip)

set -euo pipefail
cd "$(dirname "$0")/.."

OUT=supabase/apply_all.sql

{
  echo "/*"
  echo " * Spartans_Horizon — all migrations, in order, as one script."
  echo " * GENERATED by supabase/build_apply_all.sh. Do not edit by hand;"
  echo " * edit the individual migrations and regenerate."
  echo " *"
  echo " * Safe to re-run: every statement is guarded (CREATE TABLE IF NOT EXISTS,"
  echo " * DROP POLICY IF EXISTS before CREATE POLICY, CREATE OR REPLACE FUNCTION,"
  echo " * DROP CONSTRAINT IF EXISTS before ADD CONSTRAINT)."
  echo " *"
  echo " * The SQL Editor runs a multi-statement script in one implicit transaction, so"
  echo " * if any statement fails the whole script rolls back — never a partial apply."
  echo " */"
  echo

  for f in supabase/migrations/*.sql; do
    echo ""
    echo "-- ============================================================================"
    echo "-- $(basename "$f")"
    echo "-- ============================================================================"
    echo ""
    cat "$f"
    echo ""
  done
} > "$OUT"

# A truncated copy/paste is how this file got mangled once already; fail loudly if a
# leading keyword character went missing.
if grep -nqE '^[[:space:]]*(REATE|LTER|RANT|EVOKE|ROP|NSERT|ELECT)\b' "$OUT"; then
  echo "ERROR: clipped SQL keyword detected in $OUT" >&2
  grep -nE '^[[:space:]]*(REATE|LTER|RANT|EVOKE|ROP|NSERT|ELECT)\b' "$OUT" >&2
  exit 1
fi

echo "Wrote $OUT — $(wc -l < "$OUT") lines, $(wc -c < "$OUT") bytes"
echo "Migrations included:"
for f in supabase/migrations/*.sql; do echo "  $(basename "$f")"; done

if [ "${1:-}" = "--copy" ]; then
  if command -v xclip >/dev/null; then
    xclip -selection clipboard < "$OUT"
    echo "Copied to clipboard."
  else
    echo "xclip not found; copy manually." >&2
  fi
fi
